version: "3.3"

services:
  postgres:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: complitech_api_db
    ports:
      - "5432:5432"
  app:
    container_name: complitech-api
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres