server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/complitech_api_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      format_sql: true
      hbm2ddl.auto: validate

jwt_secret: SECRET

api:
  version: v1
  description: This API is a test task for Complitech.
